/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calls` | `/calls`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/deliveries` | `/deliveries`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routes` | `/routes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sync` | `/sync`; params?: Router.UnknownInputParams; } | { pathname: `/call/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/delivery/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/route/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calls` | `/calls`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/deliveries` | `/deliveries`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/routes` | `/routes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sync` | `/sync`; params?: Router.UnknownOutputParams; } | { pathname: `/call/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/delivery/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/route/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calls${`?${string}` | `#${string}` | ''}` | `/calls${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/deliveries${`?${string}` | `#${string}` | ''}` | `/deliveries${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/routes${`?${string}` | `#${string}` | ''}` | `/routes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sync${`?${string}` | `#${string}` | ''}` | `/sync${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calls` | `/calls`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/deliveries` | `/deliveries`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/routes` | `/routes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sync` | `/sync`; params?: Router.UnknownInputParams; } | `/call/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/delivery/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/route/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/call/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/delivery/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/route/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
